apiVersion: snapshot.mongodbatlas.crossplane.io/v1alpha1
kind: BackupSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: snapshot/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterName: cluster-test
    description: myDescription
    projectId: ${mongodbatlas_cluster.my_cluster.project_id}
    retentionInDays: 1

---

apiVersion: cloud.mongodbatlas.crossplane.io/v1alpha1
kind: BackupSnapshotRestoreJob
metadata:
  annotations:
    meta.upbound.io/example-id: snapshot/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterName: MyCluster
    deliveryType:
    - download: true
    projectId: 5cf5a45a9ccf6400e60981b6
    snapshotId: ${mongodbatlas_cloud_backup_snapshot.test.snapshot_id}

---

apiVersion: cluster.mongodbatlas.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: snapshot/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
spec:
  forProvider:
    cloudBackup: true
    name: MyCluster
    projectId: 5cf5a45a9ccf6400e60981b6
    providerInstanceSizeName: M10
    providerName: AWS
    providerRegionName: EU_WEST_2

---

