apiVersion: private.mongodbatlas.crossplane.io/v1alpha1
kind: EndpointRegionalMode
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/endpointregionalmode
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    enabled: true
    projectId: ${var.atlasprojectid}

---

apiVersion: cluster.mongodbatlas.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/endpointregionalmode
  labels:
    testing.upbound.io/example-name: cluster-atlas
  name: cluster-atlas
spec:
  forProvider:
    autoScalingDiskGbEnabled: true
    cloudBackup: true
    clusterType: GEOSHARDED
    mongoDbMajorVersion: "5.0"
    name: ${var.cluster_name}
    projectId: ${var.atlasprojectid}
    providerInstanceSizeName: M30
    providerName: AWS
    replicationSpecs:
    - numShards: 2
      regionsConfig:
      - electableNodes: 3
        priority: 7
        readOnlyNodes: 0
        regionName: ${var.atlas_region_east}
      - electableNodes: 2
        priority: 6
        readOnlyNodes: 0
        regionName: ${var.atlas_region_west}
      zoneName: Zone 1

---

apiVersion: privatelink.mongodbatlas.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/endpointregionalmode
  labels:
    testing.upbound.io/example-name: test_east
  name: test-east
spec:
  forProvider:
    projectId: var.atlasprojectid

---

apiVersion: privatelink.mongodbatlas.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: private/v1alpha1/endpointregionalmode
  labels:
    testing.upbound.io/example-name: test_west
  name: test-west
spec:
  forProvider:
    projectId: ${var.atlasprojectid}
    providerName: AWS
    region: US_WEST_1

---

