apiVersion: online.mongodbatlas.crossplane.io/v1alpha1
kind: Archive
metadata:
  annotations:
    meta.upbound.io/example-id: online/v1alpha1/archive
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterName: ${var.cluster_name}
    collName: ${var.collection_name}
    criteria:
    - dateField: created
      expireAfterDays: 5
      type: DATE
    dbName: ${var.database_name}
    partitionFields:
    - fieldName: firstName
      order: 0
    - fieldName: lastName
      order: 1
    projectId: ${var.project_id}
    schedule:
    - endHour: 1
      endMinute: 1
      startHour: 1
      startMinute: 1
      type: DAILY

---

