/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SettingsOrgConfigObservation struct {

	// List that contains the approved domains from which organization users can log in.
	DomainAllowList []*string `json:"domainAllowList,omitempty" tf:"domain_allow_list,omitempty"`

	// Flag that indicates whether domain restriction is enabled for the connected organization.
	DomainRestrictionEnabled *bool `json:"domainRestrictionEnabled,omitempty" tf:"domain_restriction_enabled,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
	FederationSettingsID *string `json:"federationSettingsId,omitempty" tf:"federation_settings_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// List that contains the default roles granted to users who authenticate through the IdP in a connected organization.
	PostAuthRoleGrants []*string `json:"postAuthRoleGrants,omitempty" tf:"post_auth_role_grants,omitempty"`
}

type SettingsOrgConfigParameters struct {

	// List that contains the approved domains from which organization users can log in.
	// +kubebuilder:validation:Optional
	DomainAllowList []*string `json:"domainAllowList,omitempty" tf:"domain_allow_list,omitempty"`

	// Flag that indicates whether domain restriction is enabled for the connected organization.
	// +kubebuilder:validation:Optional
	DomainRestrictionEnabled *bool `json:"domainRestrictionEnabled,omitempty" tf:"domain_restriction_enabled,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
	// +kubebuilder:validation:Optional
	FederationSettingsID *string `json:"federationSettingsId,omitempty" tf:"federation_settings_id,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// List that contains the default roles granted to users who authenticate through the IdP in a connected organization.
	// +kubebuilder:validation:Optional
	PostAuthRoleGrants []*string `json:"postAuthRoleGrants,omitempty" tf:"post_auth_role_grants,omitempty"`
}

// SettingsOrgConfigSpec defines the desired state of SettingsOrgConfig
type SettingsOrgConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingsOrgConfigParameters `json:"forProvider"`
}

// SettingsOrgConfigStatus defines the observed state of SettingsOrgConfig.
type SettingsOrgConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsOrgConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsOrgConfig is the Schema for the SettingsOrgConfigs API. Provides a federated settings Organization Configuration.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mongodbatlas}
type SettingsOrgConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.domainRestrictionEnabled)",message="domainRestrictionEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.federationSettingsId)",message="federationSettingsId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.identityProviderId)",message="identityProviderId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.orgId)",message="orgId is a required parameter"
	Spec   SettingsOrgConfigSpec   `json:"spec"`
	Status SettingsOrgConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsOrgConfigList contains a list of SettingsOrgConfigs
type SettingsOrgConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SettingsOrgConfig `json:"items"`
}

// Repository type metadata.
var (
	SettingsOrgConfig_Kind             = "SettingsOrgConfig"
	SettingsOrgConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SettingsOrgConfig_Kind}.String()
	SettingsOrgConfig_KindAPIVersion   = SettingsOrgConfig_Kind + "." + CRDGroupVersion.String()
	SettingsOrgConfig_GroupVersionKind = CRDGroupVersion.WithKind(SettingsOrgConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&SettingsOrgConfig{}, &SettingsOrgConfigList{})
}
