/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this Configuration
func (mg *Configuration) GetTerraformResourceType() string {
	return "mongodbatlas_alert_configuration"
}

// GetConnectionDetailsMapping for this Configuration
func (tr *Configuration) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"notification[*].api_token": "spec.forProvider.notification[*].apiTokenSecretRef", "notification[*].datadog_api_key": "spec.forProvider.notification[*].datadogApiKeySecretRef", "notification[*].microsoft_teams_webhook_url": "spec.forProvider.notification[*].microsoftTeamsWebhookUrlSecretRef", "notification[*].ops_genie_api_key": "spec.forProvider.notification[*].opsGenieApiKeySecretRef", "notification[*].service_key": "spec.forProvider.notification[*].serviceKeySecretRef", "notification[*].victor_ops_api_key": "spec.forProvider.notification[*].victorOpsApiKeySecretRef", "notification[*].victor_ops_routing_key": "spec.forProvider.notification[*].victorOpsRoutingKeySecretRef", "notification[*].webhook_secret": "spec.forProvider.notification[*].webhookSecretSecretRef", "notification[*].webhook_url": "spec.forProvider.notification[*].webhookUrlSecretRef"}
}

// GetObservation of this Configuration
func (tr *Configuration) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this Configuration
func (tr *Configuration) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this Configuration
func (tr *Configuration) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this Configuration
func (tr *Configuration) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this Configuration
func (tr *Configuration) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this Configuration using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *Configuration) LateInitialize(attrs []byte) (bool, error) {
	params := &ConfigurationParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *Configuration) GetTerraformSchemaVersion() int {
	return 0
}
