/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicy of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetManagementPolicy() xpv1.ManagementPolicy {
	return mg.Spec.ManagementPolicy
}

// GetProviderConfigReference of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

/*
GetProviderReference of this DNSConfigurationClusterAws.
Deprecated: Use GetProviderConfigReference.
*/
func (mg *DNSConfigurationClusterAws) GetProviderReference() *xpv1.Reference {
	return mg.Spec.ProviderReference
}

// GetPublishConnectionDetailsTo of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicy of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetManagementPolicy(r xpv1.ManagementPolicy) {
	mg.Spec.ManagementPolicy = r
}

// SetProviderConfigReference of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

/*
SetProviderReference of this DNSConfigurationClusterAws.
Deprecated: Use SetProviderConfigReference.
*/
func (mg *DNSConfigurationClusterAws) SetProviderReference(r *xpv1.Reference) {
	mg.Spec.ProviderReference = r
}

// SetPublishConnectionDetailsTo of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this DNSConfigurationClusterAws.
func (mg *DNSConfigurationClusterAws) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
