//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAws) DeepCopyInto(out *DNSConfigurationClusterAws) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAws.
func (in *DNSConfigurationClusterAws) DeepCopy() *DNSConfigurationClusterAws {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAws)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSConfigurationClusterAws) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAwsList) DeepCopyInto(out *DNSConfigurationClusterAwsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSConfigurationClusterAws, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAwsList.
func (in *DNSConfigurationClusterAwsList) DeepCopy() *DNSConfigurationClusterAwsList {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAwsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSConfigurationClusterAwsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAwsObservation) DeepCopyInto(out *DNSConfigurationClusterAwsObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAwsObservation.
func (in *DNSConfigurationClusterAwsObservation) DeepCopy() *DNSConfigurationClusterAwsObservation {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAwsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAwsParameters) DeepCopyInto(out *DNSConfigurationClusterAwsParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAwsParameters.
func (in *DNSConfigurationClusterAwsParameters) DeepCopy() *DNSConfigurationClusterAwsParameters {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAwsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAwsSpec) DeepCopyInto(out *DNSConfigurationClusterAwsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAwsSpec.
func (in *DNSConfigurationClusterAwsSpec) DeepCopy() *DNSConfigurationClusterAwsSpec {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAwsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfigurationClusterAwsStatus) DeepCopyInto(out *DNSConfigurationClusterAwsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfigurationClusterAwsStatus.
func (in *DNSConfigurationClusterAwsStatus) DeepCopy() *DNSConfigurationClusterAwsStatus {
	if in == nil {
		return nil
	}
	out := new(DNSConfigurationClusterAwsStatus)
	in.DeepCopyInto(out)
	return out
}
