apiVersion: privatelink.mongodbatlas.crossplane.io/v1alpha1
kind: EndpointServiceDataFederationOnlineArchive
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/endpointservicedatafederationonlinearchive
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    comment: Test
    endpointId: <PRIVATE-ENDPOINT-SERVICE-ID>
    projectId: ${mongodbatlas_project.atlas-project.id}
    providerName: AWS

---

apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/endpointservicedatafederationonlinearchive
  labels:
    testing.upbound.io/example-name: atlas-project
  name: atlas-project
spec:
  forProvider:
    name: ${var.atlas_project_name}
    orgId: ${var.atlas_org_id}

---

